Map<String, String> categoryIcons = {
  'Kafe': 'lib/assets/icons/Kafe.png',
  'Lokanta': 'lib/assets/icons/Lokanta.png',
  'Tost, Dondurma, Çikolata': 'lib/assets/icons/Tost.png',
  'Fitness': 'lib/assets/icons/Fitness.png',
  'Güzellik': 'lib/assets/icons/Güzellik.png',
  'Eğitim': 'lib/assets/icons/Eğitim.png',
  'Aktar': 'lib/assets/icons/Aktar.png',
  'Kuruyemiş': 'lib/assets/icons/Kuruyemiş.png',
  'Kasap': 'lib/assets/icons/Kasap.png',
  'Berber': 'lib/assets/icons/Berber.png',
  'Nakliyat': 'lib/assets/icons/Nakliyat.png',
  'Kahvaltı': 'lib/assets/icons/Kahvaltı.png',
  'İnternet': 'lib/assets/icons/İnternet.png',
  'Terzi': 'lib/assets/icons/Terzi.png',
  'Sağlık, Epilasyon': 'lib/assets/icons/Sağlık.png',
  'Oto Yıkama': 'lib/assets/icons/Oto Yıkama.png',
  'Ulaşım': 'lib/assets/icons/Ulaşım.png',
  'Kiralama': 'lib/assets/icons/Kiralama.png',
  'Giyim': 'lib/assets/icons/Giyim.png',
  'Ev Ürünleri': 'lib/assets/icons/Ev ürünleri.png',
  'İnşaat Malzemeleri': 'lib/assets/icons/İnşaat.png',
  'Akaryakıt': 'lib/assets/icons/Akaryakıt.png',
  'Usta, Tadilat': 'lib/assets/icons/Usta.png',
  'Konsol Oyunları': 'lib/assets/icons/Konsol.png',
};
